name: Release

on:
  push:
    tags:
      - 'v*'  # 예: v0.1, v1.2.3 등 태그 push 시 자동 실행

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up tar.gz and zip
        run: |
          mkdir -p dist
          tar -czf dist/ablestack-qemu-exec-tools.tar.gz . --exclude-vcs
          zip -r dist/ablestack-qemu-exec-tools.zip . -x '*.git*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/ablestack-qemu-exec-tools.tar.gz
            dist/ablestack-qemu-exec-tools.zip
