#!/usr/bin/env bash
# ---------------------------------------------------------------------
# Copyright 2026 ABLECLOUD
# ---------------------------------------------------------------------

# shellcheck disable=SC2034

FTCTL_DEFAULT_CONFIG="/etc/ablestack/ablestack-vm-ftctl.conf"

FTCTL_POLICY_DEFAULT="default"
FTCTL_DRY_RUN_DEFAULT="0"
FTCTL_RUN_DIR_DEFAULT="/run/ablestack-vm-ftctl"
FTCTL_LOG_DIR_DEFAULT="/var/log/ablestack-vm-ftctl"
FTCTL_EVENTS_LOG_DEFAULT="/var/log/ablestack-vm-ftctl/events.log"
FTCTL_LOCK_FILE_DEFAULT="/run/ablestack-vm-ftctl/lock"
FTCTL_STATE_DIR_DEFAULT="/run/ablestack-vm-ftctl/state"
FTCTL_PROFILE_DIR_DEFAULT="/etc/ablestack/ftctl.d"

FTCTL_DEFAULT_PRIMARY_URI_DEFAULT="qemu:///system"
FTCTL_DEFAULT_PEER_URI_DEFAULT="qemu+ssh://peer/system"

FTCTL_HEALTH_INTERVAL_SEC_DEFAULT="2"
FTCTL_FAILOVER_CONFIRM_SEC_DEFAULT="4"
FTCTL_FENCING_TIMEOUT_SEC_DEFAULT="15"
FTCTL_TRANSIENT_NET_GRACE_SEC_DEFAULT="3"
FTCTL_MAX_REARM_ATTEMPTS_DEFAULT="5"
FTCTL_REARM_BACKOFF_SEC_DEFAULT="2"

FTCTL_BLOCKCOPY_BANDWIDTH_MIB_DEFAULT="0"
FTCTL_BLOCKCOPY_SYNC_WRITES_DEFAULT="1"
FTCTL_BLOCKCOPY_GRANULARITY_DEFAULT="0"

FTCTL_XCOLO_QMP_TIMEOUT_SEC_DEFAULT="3"
FTCTL_XCOLO_CONTROL_NET_DEFAULT=""
FTCTL_XCOLO_REPL_NET_DEFAULT=""

FTCTL_CONFIG_PATH=""
FTCTL_POLICY=""
FTCTL_DRY_RUN=""
FTCTL_RUN_DIR=""
FTCTL_LOG_DIR=""
FTCTL_EVENTS_LOG=""
FTCTL_LOCK_FILE=""
FTCTL_STATE_DIR=""
FTCTL_PROFILE_DIR=""
FTCTL_DEFAULT_PRIMARY_URI=""
FTCTL_DEFAULT_PEER_URI=""
FTCTL_HEALTH_INTERVAL_SEC=""
FTCTL_FAILOVER_CONFIRM_SEC=""
FTCTL_FENCING_TIMEOUT_SEC=""
FTCTL_TRANSIENT_NET_GRACE_SEC=""
FTCTL_MAX_REARM_ATTEMPTS=""
FTCTL_REARM_BACKOFF_SEC=""
FTCTL_BLOCKCOPY_BANDWIDTH_MIB=""
FTCTL_BLOCKCOPY_SYNC_WRITES=""
FTCTL_BLOCKCOPY_GRANULARITY=""
FTCTL_XCOLO_QMP_TIMEOUT_SEC=""
FTCTL_XCOLO_CONTROL_NET=""
FTCTL_XCOLO_REPL_NET=""

ftctl_config_init_defaults() {
  FTCTL_CONFIG_PATH="${FTCTL_DEFAULT_CONFIG}"
  FTCTL_POLICY="${FTCTL_POLICY_DEFAULT}"
  FTCTL_DRY_RUN="${FTCTL_DRY_RUN_DEFAULT}"
  FTCTL_RUN_DIR="${FTCTL_RUN_DIR_DEFAULT}"
  FTCTL_LOG_DIR="${FTCTL_LOG_DIR_DEFAULT}"
  FTCTL_EVENTS_LOG="${FTCTL_EVENTS_LOG_DEFAULT}"
  FTCTL_LOCK_FILE="${FTCTL_LOCK_FILE_DEFAULT}"
  FTCTL_STATE_DIR="${FTCTL_STATE_DIR_DEFAULT}"
  FTCTL_PROFILE_DIR="${FTCTL_PROFILE_DIR_DEFAULT}"
  FTCTL_DEFAULT_PRIMARY_URI="${FTCTL_DEFAULT_PRIMARY_URI_DEFAULT}"
  FTCTL_DEFAULT_PEER_URI="${FTCTL_DEFAULT_PEER_URI_DEFAULT}"
  FTCTL_HEALTH_INTERVAL_SEC="${FTCTL_HEALTH_INTERVAL_SEC_DEFAULT}"
  FTCTL_FAILOVER_CONFIRM_SEC="${FTCTL_FAILOVER_CONFIRM_SEC_DEFAULT}"
  FTCTL_FENCING_TIMEOUT_SEC="${FTCTL_FENCING_TIMEOUT_SEC_DEFAULT}"
  FTCTL_TRANSIENT_NET_GRACE_SEC="${FTCTL_TRANSIENT_NET_GRACE_SEC_DEFAULT}"
  FTCTL_MAX_REARM_ATTEMPTS="${FTCTL_MAX_REARM_ATTEMPTS_DEFAULT}"
  FTCTL_REARM_BACKOFF_SEC="${FTCTL_REARM_BACKOFF_SEC_DEFAULT}"
  FTCTL_BLOCKCOPY_BANDWIDTH_MIB="${FTCTL_BLOCKCOPY_BANDWIDTH_MIB_DEFAULT}"
  FTCTL_BLOCKCOPY_SYNC_WRITES="${FTCTL_BLOCKCOPY_SYNC_WRITES_DEFAULT}"
  FTCTL_BLOCKCOPY_GRANULARITY="${FTCTL_BLOCKCOPY_GRANULARITY_DEFAULT}"
  FTCTL_XCOLO_QMP_TIMEOUT_SEC="${FTCTL_XCOLO_QMP_TIMEOUT_SEC_DEFAULT}"
  FTCTL_XCOLO_CONTROL_NET="${FTCTL_XCOLO_CONTROL_NET_DEFAULT}"
  FTCTL_XCOLO_REPL_NET="${FTCTL_XCOLO_REPL_NET_DEFAULT}"
}

ftctl_config_apply_cli() {
  local cfg="${1-}"
  local pol="${2-}"
  local dry="${3-}"
  [[ -n "${cfg}" ]] && FTCTL_CONFIG_PATH="${cfg}"
  [[ -n "${pol}" ]] && FTCTL_POLICY="${pol}"
  [[ -n "${dry}" ]] && FTCTL_DRY_RUN="${dry}"
}

ftctl_config_load_file() {
  local path="${1-}"
  [[ -n "${path}" && -f "${path}" ]] || return 0
  set -a
  # shellcheck source=/dev/null
  source "${path}"
  set +a
}

ftctl_ensure_runtime_dirs() {
  ftctl_ensure_dir "${FTCTL_RUN_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_LOG_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_STATE_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_PROFILE_DIR}" "0755"
  ftctl_ensure_dir "$(dirname "${FTCTL_EVENTS_LOG}")" "0755"
}
